### ISSUE TITLE
vue组件—双向绑定

### ISSUE THREAD

**Issue by elrictang** [elrictang/elrictang.github.io#3]
https://rokudomukuro.github.io/2018/08/23/vue-custom-v-model/ 

 webGIS web前端开发 动漫迷,又是美好的一天，未完待续、、、

**Comment by RokudoMukuro** [comment]
# 自己占楼
## 我瞅瞅支不支持maekdown语法
***
### 一楼
#### 二楼
开始测试。。。

**Comment by RokudoMukuro** [comment]
***
我擦，真可以支持md语法
***

**Comment by elrictang** [comment]
### 我擦
***
#### 真可以支持md语法
***
##### over
